apiVersion: v2
name: kubevirtbmc
version: 0.4.0
description: A Helm chart for KubeVirtBMC
type: application
keywords:
- kubevirt
- cdi
- vm
- bmc
- ipmi
- redfish
home: https://github.com/starbops/kubevirtbmc
sources:
- https://github.com/starbops/kubevirtbmc
maintainers:
- name: starbops
  email: starbops@hey.com
  url: https://www.zespre.com
appVersion: v0.7.0
