apiVersion: bmc.kubevirt.io/v1beta1
kind: VirtualMachineBMC
metadata:
  labels:
    app.kubernetes.io/name: kubevirtbmc
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinebmc-sample
spec:
  virtualMachineRef:
    name: my-virtual-machine
  authSecretRef:
    name: my-bmc-credentials
