apiVersion: virtualmachine.kubevirt.io/v1alpha1
kind: VirtualMachineBMC
metadata:
  labels:
    app.kubernetes.io/name: virtualmachinebmc
    app.kubernetes.io/instance: virtualmachinebmc-sample
    app.kubernetes.io/part-of: kubevirtbmc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubevirtbmc
  name: virtualmachinebmc-sample
  namespace: kubevirtbmc-system
spec:
  username: admin
  password: password
  vmNamespace: default
  vmName: test-vm
