name: Helm Chart E2E

on:
  pull_request:
    types:
    - opened
    - synchronize
# for testing as of now 

jobs:
  helm-e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      REPO: starbops
      MANAGER: virtbmc-controller
      AGENT: virtbmc
      VERSION: ${{ github.event_name == 'pull_request' && format('pr-{0}-helm', github.event.number) || format('helm-{0}', github.sha) }}
      GIT_COMMIT: ${{ github.sha }}
      DEPLOY_WITH_HELM_CHART: "true"
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
    - name: Set up Helm
      uses: azure/setup-helm@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REPO }}/${{ env.MANAGER }}
          ${{ env.REPO }}/${{ env.AGENT }}
    - name: Docker build manager
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        build-args: |
          LINKFLAGS=-X main.AppVersion=${{ env.VERSION }} -X main.GitCommit=${{ env.GIT_COMMIT }}
        file: Dockerfile
        push: false
        load: true
        tags: ${{ env.REPO }}/${{ env.MANAGER }}:${{ env.VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Docker build agent
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        build-args: |
          LINKFLAGS=-X main.AppVersion=${{ env.VERSION }} -X main.GitCommit=${{ env.GIT_COMMIT }}
        file: Dockerfile.virtbmc
        push: false
        load: true
        tags: ${{ env.REPO }}/${{ env.AGENT }}:${{ env.VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Run helm-based end-to-end testing
      run: make local-e2e-test

